# Generated by Django 2.2.3 on 2019-07-23 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disney', '0003_auto_20190723_1245'),
    ]

    operations = [
        migrations.CreateModel(
            name='Name',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
    ]
